#!/bin/sh

#
# bootstrap

set -e

echo "Setting up your environment..."

#
# Check for Bundler
#
if test ! $(which bundle)
then
  echo -n " x You need to install Bundler:"
  echo "  gem install bundler"
  exit
fi

#
# Install gems
#
echo "Install gems"
bundle install --quiet

#
# Starting local jekyll server
#
echo "Starting jekyll server at http://localhost:4000/"
bundle exec jekyll serve

echo "Done!"
